sudo: required
matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    language: node_js
    node_js: '12'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
- /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn build --linux --win --mac"
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: rp5UNy10nrB7QpaWQXqcYnj+f7rOj4i1SgecJJWl6+cfh2C/xNFsq3vtlWR8my5l0Xe+7gBy61Tu+Yi/3lq2ACUUEnTaYZTzj/pOdB8x7qy5yiMe2SJ8AaOGDhcuLNnHmn3SsnglC/OQrLqFQcdzx1n8NwI1HfRWZswBvYr5ZBc/I7bt+094TG5VTxIQcUAPrZyII0R5j4EIFdoQpenlUC/HPK3tNfftQfSGlUrQovALxOFmrdJlM6QsAxpnka/gojGEENtmZpZgJkUYNSU00f8jfkkKpFPLDoJPxLw0Cn2uL1Hn+S00YveOe6Lu36DAIW4pM7rV7GDSS1gxkDVcIvhxrXsaoOGKE4YTtuObJ3PhaLPBcW0C+RBVpGA7auFgco6fjQ6ga+azzyNJjik8ggGJdGZF04RfILb5z8MJmt8BzZV/r8wd6fAZtkgiE/mO+X4wzxzPYx6o5GrM+TC8/UWJJwDzX/gi587CQlK4MbZ3OSu8qdY+XmmKVgEwfwk7H7uIhNxZj93NH5UfpsaIVbnmfSxmZq7pGZ5IByY9SA9mzUyhG3HEOmaNcsvgA+T36ymOuhAtkKU2lMzHvpWHXVlatHqMjl4y0QaAItwEua2T8gfjw4CmuPIE7HODwyH4dijYbtoFQ9+Yzs5y6V9lyptO5fN3hoTs6q4naTYRX24=
  file:
    - release/js-journal-mac.zip
    - release/js-journal-mac.dmg
    - release/js-journal-mac.dmg.blockmap
    - release/js-journal-linux.AppImage
    - release/js-journal-linux.snap
    - release/js-journal-win.exe
    - release/js-journal-win.exe.blockmap
  on:
    repo: wnuke/js-journal
